---
- name: Retrieve facts from Junos devices
  hosts: network
  roles:
      - Juniper.junos
  connection: local
  gather_facts: yes
#  vars_files:
#      - data/network.yaml
  tasks:
      - name: Retrieve information from devices running Junos OS
        junos_get_facts:
          host: "{{ inventory_hostname }}"
          user: "{{ junos_username }}"
          passwd: "{{ junos_password }}"
        register: junos

#      - name: Debug
#        debug:
#          msg: "Network data is {{ base_config }}"

      - name: Create configuration for push
        template:
          src: host_vars/update_pce.j2
          dest: config/update-{{ junos.facts.hostname }}.conf

      - name: Push configuration to device
        junos_install_config:
          host: "{{ inventory_hostname }}"
          user: "{{ junos_username }}"
          passwd: "{{ junos_password }}"
          file: config/update-{{ junos.facts.hostname }}.conf
          overwrite: false
    #  - name: Create configuration snippets for SNMP
    #    template:
    #      src: junos-snmp.conf.j2
    #      dest: configs/snmp-{{ junos.facts.hostname }}.conf

#      - name: Push SNMP configuration to device
#        junos_install_config:
#          host: "{{ inventory_hostname }}"
#          user: "{{ junos_username }}"
#          passwd: "{{ junos_password }}"
#          file: configs/snmp-{{ junos.facts.hostname }}.conf
#          overwrite: false

#      - name: Create configuration snippets for sensors
#        template:
#          src: junos-sensor.conf.j2
#          dest: configs/sensor-{{ junos.facts.hostname }}.conf

#     - name: Push Sensor configuration to device
#        junos_install_config:
#          host: "{{ inventory_hostname }}"
#          user: "{{ junos_username }}"
#          passwd: "{{ junos_password }}"
#          file: configs/sensor-{{ junos.facts.hostname }}.conf
#          overwrite: false
